/**
 * Copyright 2024-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generato
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

/**
 *  - MARKET: A [market order](https://en.wikipedia.org/wiki/Order_(exchange)#Market_order)  - LIMIT: A [limit order](https://en.wikipedia.org/wiki/Order_(exchange)#Limit_order)  - STOP: A stop order is an order that becomes a market order when triggered  - STOP_LIMIT: A stop order is a limit order that doesn\'t go on the book until it hits the stop price  - BRACKET: A bracket order is a way to mitigate potential losses in volatile markets, consisting of a limit price leg and a stop trigger price. Note: Bracket orders are currently in closed beta and may be disabled to resolve issues during testing. Stay tuned for the public release coming soon.
 */
export enum OrderType {
  UnknownOrderType = 'UNKNOWN_ORDER_TYPE',
  Market = 'MARKET',
  Limit = 'LIMIT',
  Stop = 'STOP',
  StopLimit = 'STOP_LIMIT',
  Bracket = 'BRACKET',
}
